# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'play.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GAME(object):
    def setupUi(self, GAME):
        GAME.setObjectName("GAME")
        GAME.resize(1155, 646)
        self.centralwidget = QtWidgets.QWidget(GAME)
        self.centralwidget.setObjectName("centralwidget")
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setGeometry(QtCore.QRect(760, 110, 171, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(17)
        self.timeLabel.setFont(font)
        self.timeLabel.setObjectName("timeLabel")
        self.roundLabel = QtWidgets.QLabel(self.centralwidget)
        self.roundLabel.setGeometry(QtCore.QRect(760, 180, 171, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(17)
        self.roundLabel.setFont(font)
        self.roundLabel.setObjectName("roundLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(780, 280, 81, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1000, 280, 71, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(17)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.playerLabel = QtWidgets.QLabel(self.centralwidget)
        self.playerLabel.setGeometry(QtCore.QRect(760, 350, 120, 108))
        self.playerLabel.setText("")
        self.playerLabel.setObjectName("playerLabel")
        self.robotLabel = QtWidgets.QLabel(self.centralwidget)
        self.robotLabel.setGeometry(QtCore.QRect(980, 350, 120, 108))
        self.robotLabel.setText("")
        self.robotLabel.setObjectName("robotLabel")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(900, 370, 51, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.scoreLabel = QtWidgets.QLabel(self.centralwidget)
        self.scoreLabel.setGeometry(QtCore.QRect(760, 470, 251, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.scoreLabel.setFont(font)
        self.scoreLabel.setObjectName("scoreLabel")
        self.continueButton = QtWidgets.QPushButton(self.centralwidget)
        self.continueButton.setGeometry(QtCore.QRect(760, 530, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.continueButton.setFont(font)
        self.continueButton.setObjectName("continueButton")
        self.returnButton = QtWidgets.QPushButton(self.centralwidget)
        self.returnButton.setGeometry(QtCore.QRect(960, 530, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.returnButton.setFont(font)
        self.returnButton.setObjectName("returnButton")
        self.cameraView = QtWidgets.QGraphicsView(self.centralwidget)
        self.cameraView.setGeometry(QtCore.QRect(40, 40, 643, 483))
        self.cameraView.setObjectName("cameraView")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(310, 540, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.photoLabel = QtWidgets.QLabel(self.centralwidget)
        self.photoLabel.setGeometry(QtCore.QRect(760, 10, 100, 100))
        self.photoLabel.setText("")
        self.photoLabel.setObjectName("photoLabel")
        self.welcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.welcomeLabel.setGeometry(QtCore.QRect(920, 40, 151, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setText("")
        self.welcomeLabel.setObjectName("welcomeLabel")
        GAME.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GAME)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1155, 26))
        self.menubar.setObjectName("menubar")
        GAME.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GAME)
        self.statusbar.setObjectName("statusbar")
        GAME.setStatusBar(self.statusbar)

        self.retranslateUi(GAME)
        QtCore.QMetaObject.connectSlotsByName(GAME)

    def retranslateUi(self, GAME):
        _translate = QtCore.QCoreApplication.translate
        GAME.setWindowTitle(_translate("GAME", "MainWindow"))
        self.timeLabel.setText(_translate("GAME", "倒计时"))
        self.roundLabel.setText(_translate("GAME", "Round"))
        self.label_3.setText(_translate("GAME", "玩家"))
        self.label_4.setText(_translate("GAME", "电脑"))
        self.label_7.setText(_translate("GAME", "   VS"))
        self.scoreLabel.setText(_translate("GAME", "玩家累计得分："))
        self.continueButton.setText(_translate("GAME", "继续"))
        self.returnButton.setText(_translate("GAME", "返回"))
        self.startButton.setText(_translate("GAME", "开始游戏"))
